name: Python CI Cloud Run Deployment

# TODO: change stage deployment

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
# ------------- Lint & tests -------------
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - uses: pre-commit/action@v3.0.1
        with: { extra_args: --all-files }

  pytest:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest
      - name: Run tests
        run: |
          pytest tests/
