name: Python CI/CD Cloud Run Deployment

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
# ------------- Pre-commits & Tests -------------
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - uses: pre-commit/action@v3.0.1
        with: { extra_args: --all-files }

  pytest:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest
      - name: Run tests
        run: |
          pytest tests/

# ------------- Deployment -------------
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: pytest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        workload_identity_provider: projects/24294949938/locations/global/workloadIdentityPools/github-pool/providers/github-provider
        service_account: github-deployer@sentivista-453008.iam.gserviceaccount.com
        create_credentials_file: true
        export_environment_variables: true
        universe: googleapis.com
        cleanup_credentials: true
        access_token_lifetime: 3600s
        access_token_scopes: https://www.googleapis.com/auth/cloud-platform
        id_token_include_email: false

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: sentivista-453008

    - name: Docker Image
      run: |
        gcloud auth configure-docker europe-west1-docker.pkg.dev
        docker build -t europe-west1-docker.pkg.dev/sentivista-453008/automatic-deployment/app .
        docker push europe-west1-docker.pkg.dev/sentivista-453008/automatic-deployment/app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy app \
          --image europe-west1-docker.pkg.dev/sentivista-453008/automatic-deployment/app \
          --region europe-west1 \
          --platform managed \
          --allow-unauthenticated
